print("Enter first number.")
a=float(input())
b=float(input("Enter second number."))
print("Press + for addition.\nPress - for subtration.\nPress * multiplication.\nPress / for division.\n")
c=input()
if c=="+": print(a+b)
elif c =="-":print(a-b)
elif c=="*":print(a*b)
elif c=="/":print(a/b)
else: print('wrong input')
